{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "b4820a10-a1a2-4d07-9613-45029a42f119",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-25 00:18:08.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.727 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.730 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.730 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.732 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.733 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.733 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.737 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.737 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.738 Session state does not function when running a script without `streamlit run`\n",
      "2025-05-25 00:18:08.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-25 00:18:08.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# Streamlit Application Code \n",
    "\n",
    "import streamlit as st\n",
    "import cv2\n",
    "import numpy as np\n",
    "from skimage.feature import hog\n",
    "import joblib\n",
    "import os\n",
    "from PIL import Image\n",
    "\n",
    "\n",
    "IMG_SIZE = (128, 128) # The size you resized images to for feature extraction\n",
    "MODEL_PATH = \"knn_model.pkl\" # Your saved model file\n",
    "SCALER_PATH = \"scaler.pkl\"   # Your saved scaler file\n",
    "TESTING_IMAGE_DIR = \"testing image\" \n",
    "\n",
    "#2. Load Model and Scaler\n",
    "@st.cache_resource\n",
    "def load_ml_assets():\n",
    "    \"\"\"Loads the trained model and scaler, caching them for Streamlit performance.\"\"\"\n",
    "    try:\n",
    "        loaded_model = joblib.load(MODEL_PATH)\n",
    "        loaded_scaler = joblib.load(SCALER_PATH)\n",
    "        return loaded_model, loaded_scaler\n",
    "    except FileNotFoundError:\n",
    "        st.error(f\"Error: Model ('{MODEL_PATH}') or Scaler ('{SCALER_PATH}') not found.\")\n",
    "        st.warning(\"Please ensure you've run 'main.ipynb' completely to train and save these files.\")\n",
    "        st.stop() # Stop the app if crucial files are missingtion as e:\n",
    "        st.error(f\"An unexpected error occurred while loading ML assets: {e}\")\n",
    "        st.stop() \n",
    "\n",
    "loaded_model, loaded_scaler = load_ml_assets()\n",
    "\n",
    "# 3. Feature Extraction Functions \n",
    "def extract_hog_features_for_prediction(img_array):\n",
    "    img_gray = cv2.cvtColor(img_array, cv2.COLOR_BGR2GRAY)\n",
    "    img_resized = cv2.resize(img_gray, IMG_SIZE)\n",
    "    features = hog(img_resized, orientations=9, pixels_per_cell=(8,8),\n",
    "                   cells_per_block=(2,2), block_norm='L2-Hys', visualize=False, transform_sqrt=True)\n",
    "    return features\n",
    "\n",
    "def extract_color_features_for_prediction(img_array):\n",
    "    img_resized = cv2.resize(img_array, IMG_SIZE)\n",
    "    hsv = cv2.cvtColor(img_resized, cv2.COLOR_BGR2HSV)\n",
    "    hist_hsv = cv2.calcHist([hsv], [0,1,2], None, [8,8,8], [0,180,0,256,0,256])\n",
    "    hist_hsv = hist_hsv.flatten()\n",
    "    return hist_hsv\n",
    "\n",
    "def get_combined_features_for_single_image(img_array):\n",
    "    hog_feats = extract_hog_features_for_prediction(img_array)\n",
    "    color_feats = extract_color_features_for_prediction(img_array)\n",
    "    if hog_feats is None or color_feats is None:\n",
    "        return None\n",
    "    return np.concatenate([hog_feats, color_feats])\n",
    "\n",
    "# 4 Prediction Function\n",
    "def predict_note(image_data):\n",
    "    # Convert image data to numpy array if it's from BytesIO (uploaded file)\n",
    "    if isinstance(image_data, bytes):\n",
    "        np_img = np.frombuffer(image_data, np.uint8)\n",
    "        img_array = cv2.imdecode(np_img, cv2.IMREAD_COLOR)\n",
    "    elif isinstance(image_data, np.ndarray):\n",
    "        img_array = image_data\n",
    "    else:\n",
    "        st.error(\"Invalid image data format.\")\n",
    "        return \"Error\"\n",
    "\n",
    "    if img_array is None:\n",
    "        st.error(\"Could not decode image.\")\n",
    "        return \"Error\"\n",
    "\n",
    "    features = get_combined_features_for_single_image(img_array)\n",
    "\n",
    "    if features is not None:\n",
    "        scaled_features = loaded_scaler.transform([features])\n",
    "        prediction = loaded_model.predict(scaled_features)[0]\n",
    "        \n",
    "        if prediction == 0:\n",
    "            return \"REAL Note\"\n",
    "        else:\n",
    "            return \"COUNTERFEIT Note\"\n",
    "    else:\n",
    "        return \"Error: Could not extract features.\"\n",
    "\n",
    "#  5. Streamlit App Layout\n",
    "st.set_page_config(page_title=\"Counterfeit Money Detector\")\n",
    "\n",
    "st.title(\" Counterfeit Money Detector\")\n",
    "st.markdown(\"Upload an image of a banknote or select a sample to predict if it's real or counterfeit.\")\n",
    "\n",
    "# File Uploader \n",
    "st.subheader(\"1. Upload Your Own Note Image\")\n",
    "uploaded_file = st.file_uploader(\"Choose an image...\", type=[\"jpg\", \"jpeg\", \"png\"])\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    \n",
    "    image = Image.open(uploaded_file).convert(\"RGB\")\n",
    "    st.image(image, caption=\"Uploaded Image\", use_column_width=True)\n",
    "    st.write(\"\") \n",
    "\n",
    "    # Convert PIL Image to OpenCV format for feature extraction\n",
    "    img_cv = np.array(image)\n",
    "    img_cv = cv2.cvtColor(img_cv, cv2.COLOR_RGB2BGR)\n",
    "\n",
    "    # Make prediction\n",
    "    prediction_result = predict_note(img_cv)\n",
    "    if \"Error\" not in prediction_result:\n",
    "        if \"REAL\" in prediction_result:\n",
    "            st.success(f\"Prediction: This appears to be a **{prediction_result}**\")\n",
    "        else:\n",
    "            st.error(f\"Prediction: This appears to be a **{prediction_result}**\")\n",
    "    else:\n",
    "        st.warning(prediction_result)\n",
    "\n",
    "\n",
    "# Sample Image Selector \n",
    "st.subheader(\"2. Or, Select a Sample Image\")\n",
    "\n",
    "# Get list of sample images\n",
    "sample_images = [\"--- Select ---\"]\n",
    "if os.path.exists(TESTING_IMAGE_DIR):\n",
    "    for f in os.listdir(TESTING_IMAGE_DIR):\n",
    "        if f.lower().endswith(('.jpg', '.jpeg', '.png')):\n",
    "            sample_images.append(f)\n",
    "else:\n",
    "    st.warning(f\"'{TESTING_IMAGE_DIR}' folder not found. No sample images loaded.\")\n",
    "\n",
    "selected_sample = st.selectbox(\"Choose a sample image from the 'testing image' folder:\", sample_images)\n",
    "\n",
    "if selected_sample != \"--- Select ---\":\n",
    "    sample_img_path = os.path.join(TESTING_IMAGE_DIR, selected_sample)\n",
    "    if os.path.exists(sample_img_path):\n",
    "        sample_image = Image.open(sample_img_path).convert(\"RGB\")\n",
    "        st.image(sample_image, caption=f\"Selected Sample: {selected_sample}\", use_column_width=True)\n",
    "        st.write(\"\")\n",
    "\n",
    "        # Convert PIL Image to OpenCV format\n",
    "        img_cv_sample = np.array(sample_image)\n",
    "        img_cv_sample = cv2.cvtColor(img_cv_sample, cv2.COLOR_RGB2BGR)\n",
    "        \n",
    "        # Make prediction\n",
    "        prediction_result_sample = predict_note(img_cv_sample)\n",
    "        if \"Error\" not in prediction_result_sample:\n",
    "            if \"REAL\" in prediction_result_sample:\n",
    "                st.success(f\"Prediction: This appears to be a **{prediction_result_sample}**\")\n",
    "            else:\n",
    "                st.error(f\"Prediction: This appears to be a **{prediction_result_sample}**\")\n",
    "        else:\n",
    "            st.warning(prediction_result_sample)\n",
    "    else:\n",
    "        st.error(f\"Sample image not found at: {sample_img_path}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "84fff49a-a9a7-49b7-aa95-219709e4f5d2",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (659043378.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[17], line 1\u001b[1;36m\u001b[0m\n\u001b[1;33m    streamlit run app.ipynb\u001b[0m\n\u001b[1;37m              ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "streamlit run app.ipynb"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
